# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Master of Culture
# email: email@site.com
description: Master of Culture is a blog on research conducted ethnographicly and data mining through A.I. and machine learning programs written an applied anthropologist and artist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.masterofculture.com" # the base hostname & protocol for your site
twitter_username: djmattlamb
github_username:  MDJML

# Build settings
markdown: kramdown
